# Generated by Django 4.1 on 2022-09-21 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-is_pinned', '-id']},
        ),
        migrations.AddField(
            model_name='notes',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
